"""new db schema

Revision ID: 39a4382b1650
Revises: 
Create Date: 2026-03-07 14:51:06.037105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a4382b1650'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('createur_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', 'createur_id', name='_nom_createur_uc')
    )
    op.create_index(op.f('ix_categories_createur_id'), 'categories', ['createur_id'], unique=False)
    op.create_table('taches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('createur_id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_echeance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priorite', sa.SmallInteger(), server_default=sa.text('2'), nullable=False),
    sa.Column('est_termine', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.CheckConstraint('priorite BETWEEN 1 AND 3', name='check_priorite_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taches_createur_id'), 'taches', ['createur_id'], unique=False)
    op.create_table('taches_categories',
    sa.Column('tache_id', sa.UUID(), nullable=False),
    sa.Column('categorie_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tache_id'], ['taches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tache_id', 'categorie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taches_categories')
    op.drop_index(op.f('ix_taches_createur_id'), table_name='taches')
    op.drop_table('taches')
    op.drop_index(op.f('ix_categories_createur_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
