"""Initial migration

Revision ID: 67c78fd445e3
Revises: 8076d03b1202
Create Date: 2026-02-20 14:41:12.005334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c78fd445e3'
down_revision: Union[str, Sequence[str], None] = '8076d03b1202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('taches',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('titre', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_echeance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priorite', sa.SmallInteger(), server_default=sa.text('2'), nullable=False),
    sa.Column('est_termine', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.CheckConstraint('priorite BETWEEN 1 AND 3', name='check_priorite_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taches_categories',
    sa.Column('tache_id', sa.UUID(), nullable=False),
    sa.Column('categorie_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tache_id'], ['taches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tache_id', 'categorie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taches_categories')
    op.drop_table('taches')
    op.drop_table('categories')
    # ### end Alembic commands ###
